In [3]:
import h5py
import keras
import tensorflow as tf
from keras.datasets import mnist
from keras.models import Sequential
from keras.models import load_model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from keras.preprocessing.image import img_to_array, load_img
from scipy.misc import imread, imresize
import imageio
import numpy as np
import PIL
import matplotlib.pyplot as plt

## data preprocessing and normalization

In [4]:
batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

## load pretrained model (99.25% CNN)

In [6]:
model = load_model('/Users/zetong/cnn.h5')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
__________

## classification demo

In [7]:
x = np.asarray(PIL.Image.open('/Users/zetong/mnist_png/testing/2/1802.png'))
img = PIL.Image.fromarray(x, mode='L')
x = x.reshape(28,28)
x = x.reshape(1,28,28,1)
x = x.astype('float32')
x /= 255

out = model.predict(x)
print("prediction:", np.argmax(out))
img

prediction: 2


## creating adversarial examples

onj is the objective function:

$\left\lVert\frac{1}{2}(\tanh(w)+1-x)\right\lVert^2_2 + cf(\frac{1}{2}(\tanh(w)+1)$

where $f(x^{\prime})$ is defined as:

$f(x^{\prime}) = max(max({Z(x^{\prime}_i: i \neq t)} - Z(x^{\prime}_t)), -k)$

get_noise function recovers $\delta$ from w and x:

$\delta = \frac{1}{2}(\tanh(w)+1) - x$

In [8]:
# w: variable, x: original vector, c: tradeoff constant, model: Keras NN, t: target class
def obj(w, x, c, model, t, k=0):
    e = (tf.tanh(w) + 1) * 0.5 - x
    return tf.linalg.norm(e)**2 + c*max(model.predict(x+e, steps=1000).max() - model.predict(x+e, steps=1000)[0][t], -k)

def get_noise(w, x):
    return (np.tanh(w) + 1) * 0.5 - x


## seaching for solution until $C(x+\delta) = t$

In [12]:
x = np.asarray(PIL.Image.open('/Users/zetong/mnist_png/testing/6/11.png'))
img = PIL.Image.fromarray(x, mode='L')
x = x.reshape(28,28)
x = x.reshape(1,28,28,1)
x = x.astype('float32')
x /= 255

e = np.zeros(x.shape)
w = 0.5 * np.log( (2*(e+x)) / (2-2*(e+x)) )
w = tf.Variable(x, dtype=tf.float32)
target = 3

optimizer = tf.train.AdamOptimizer(learning_rate=0.1).minimize(obj(w, x, 0.1, model, target))
print("original: ", np.argmax(model.predict(x)))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(50):
        result = sess.run([w,obj(w, x, 0.1, model, target)])
        noise = result[0]
        pert = get_noise(noise, x)
        predict = np.argmax(model.predict(x + pert))
        print(pert)
        print("prediction: ", predict)
        if predict == target:
            break
        sess.run(optimizer)
sess.close()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


original:  6
[[[[ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]]

  [[ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]
   [ 0.5       ]]

  [[ 0.5       ]
   [ 0.5      

[[[[ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]]

  [[ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]
   [ 0.45016605]]

  [[ 0.45016605]
   [ 0.45016605]
   [ 0.450

[[[[ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]]

  [[ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.01535213e-01]
   [ 4.0153

[[[[ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]]

  [[ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]
   [ 0.35521287]]

  [[ 0.35521287]
   [ 0.35521287]
   [ 0.355

[[[[ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]]

  [[ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01]
   [ 3.1213802e-01

[[[[ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]]

  [[ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.2729869 ]]

  [[ 0.2729869 ]
   [ 0.2729869 ]
   [ 0.272

[[[[ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]]

  [[ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01]
   [ 2.3812416e-01

[[[[ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]]

  [[ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]
   [ 0.20761353]]

  [[ 0.20761353]
   [ 0.20761353]
   [ 0.207

[[[[ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]]

  [[ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]
   [ 0.18127564]]

  [[ 0.18127564]
   [ 0.18127564]
   [ 0.181

[[[[ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]]

  [[ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]
   [ 0.15876737]]

  [[ 0.15876737]
   [ 0.15876737]
   [ 0.158

[[[[ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]]

  [[ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]
   [ 0.13965988]]

  [[ 0.13965988]
   [ 0.13965988]
   [ 0.139

[[[[ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]]

  [[ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]
   [ 0.12350029]]

  [[ 0.12350029]
   [ 0.12350029]
   [ 0.123

[[[[ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]]

  [[ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]
   [ 0.10985297]]

  [[ 0.10985297]
   [ 0.10985297]
   [ 0.109

[[[[ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]]

  [[ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]
   [ 0.09832239]]

  [[ 0.09832239]
   [ 0.09832239]
   [ 0.098

[[[[ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]]

  [[ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]
   [ 0.08856282]]

  [[ 0.08856282]
   [ 0.08856282]
   [ 0.088

[[[[ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]]

  [[ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]
   [ 0.08027932]]

  [[ 0.08027932]
   [ 0.08027932]
   [ 0.080

[[[[ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]]

  [[ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]
   [ 0.07322466]]

  [[ 0.07322466]
   [ 0.07322466]
   [ 0.073

[[[[ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]]

  [[ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]
   [ 0.06719345]]

  [[ 0.06719345]
   [ 0.06719345]
   [ 0.067

[[[[ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]]

  [[ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.20161891e-02]
   [ 6.2016

[[[[ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]]

  [[ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]
   [ 0.05755341]]

  [[ 0.05755341]
   [ 0.05755341]
   [ 0.057

[[[[ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]]

  [[ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]
   [ 0.05369037]]

  [[ 0.05369037]
   [ 0.05369037]
   [ 0.053

[[[[ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]]

  [[ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]
   [ 0.05033267]]

  [[ 0.05033267]
   [ 0.05033267]
   [ 0.050

[[[[ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]]

  [[ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]
   [ 0.04740247]]

  [[ 0.04740247]
   [ 0.04740247]
   [ 0.047

[[[[ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]]

  [[ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]
   [ 0.04483536]]

  [[ 0.04483536]
   [ 0.04483536]
   [ 0.044

[[[[ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]]

  [[ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.25779819e-02]
   [ 4.2577

[[[[ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]]

  [[ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]
   [ 0.04058588]]

  [[ 0.04058588]
   [ 0.04058588]
   [ 0.040

[[[[ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]]

  [[ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]
   [ 0.03882179]]

  [[ 0.03882179]
   [ 0.03882179]
   [ 0.038

[[[[ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]]

  [[ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]
   [ 0.03725457]]

  [[ 0.03725457]
   [ 0.03725457]
   [ 0.037

[[[[ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]]

  [[ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02]
   [ 3.5857916e-02

[[[[ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]]

  [[ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]
   [ 0.03460956]]

  [[ 0.03460956]
   [ 0.03460956]
   [ 0.034

[[[[ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]]

  [[ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]
   [ 0.03349063]]

  [[ 0.03349063]
   [ 0.03349063]
   [ 0.033

[[[[ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]]

  [[ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]
   [ 0.03248492]]

  [[ 0.03248492]
   [ 0.03248492]
   [ 0.032

[[[[ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]]

  [[ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]
   [ 0.03157869]]

  [[ 0.03157869]
   [ 0.03157869]
   [ 0.031

[[[[ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]]

  [[ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]
   [ 0.03075999]]

  [[ 0.03075999]
   [ 0.03075999]
   [ 0.030

[[[[ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]]

  [[ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.00186276e-02]
   [ 3.0018

[[[[ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]]

  [[ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]
   [ 0.02934569]]

  [[ 0.02934569]
   [ 0.02934569]
   [ 0.029

[[[[ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]]

  [[ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]
   [ 0.02873346]]

  [[ 0.02873346]
   [ 0.02873346]
   [ 0.028

[[[[ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]]

  [[ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02]
   [ 2.8175235e-02

[[[[ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]]

  [[ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]
   [ 0.02766514]]

  [[ 0.02766514]
   [ 0.02766514]
   [ 0.027

[[[[ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]]

  [[ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]
   [ 0.02719799]]

  [[ 0.02719799]
   [ 0.02719799]
   [ 0.027

[[[[ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]]

  [[ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]
   [ 0.02676922]]

  [[ 0.02676922]
   [ 0.02676922]
   [ 0.026

[[[[ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]]

  [[ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02]
   [ 2.6374906e-02

[[[[ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]]

  [[ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02]
   [ 2.6011437e-02

[[[[ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]]

  [[ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.56757438e-02]
   [ 2.5675

[[[[ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]]

  [[ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]
   [ 0.025365  ]]

  [[ 0.025365  ]
   [ 0.025365  ]
   [ 0.025

[[[[ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]]

  [[ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]
   [ 0.02507672]]

  [[ 0.02507672]
   [ 0.02507672]
   [ 0.025

[[[[ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]]

  [[ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.0248087 ]]

  [[ 0.0248087 ]
   [ 0.0248087 ]
   [ 0.024

[[[[ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]]

  [[ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02]
   [ 2.4559021e-02

[[[[ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]]

  [[ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.43258774e-02]
   [ 2.4325

[[[[ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]]

  [[ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.41076648e-02]
   [ 2.4107